# organization name, it's used to get github repo url, also in page title
name: pillarjs

# badge style, can be "flat", "flat-square" or ""
# see http://shields.io/ for details
badge_style: flat-square

# meta headers in html
title:       pillarjs
description: The BYO Framework Framework
keywords:

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
 - path-to-regexp
 - path-match
 - csrf
 - routington

# list of maintainers, this won't be sorted
maintainers:
 - name:    Doug Wilson
   github:  dougwilson   # github account, required: we link to it
   npm:     dougwilson   # npm account, required to determine lead maintainer
   twitter: blipsofadoug # twitter account, optional
   gittip:  dougwilson   # gittub badge, optional
   email:   doug@somethingdoug.com

 - name:    Jonathan Ong
   github:  jonathanong
   npm:     jongleberry
   twitter: jongleberry
   gittip:  jonathanong
   email:   me@jongleberry.com

 - name:    Jeremiah Senkpiel
   github:  fishrock123
   npm:     fishrock123
   twitter: fishrock123
   gittip:  Fishrock123
   email:   fishrock123@rocketmail.com

 - name:    Alex Kocharin
   github:  rlidwka
   npm:     rlidwka
   twitter: rlidwka
   email:   alex@kocharin.ru

 - name:    Blake Embrey
   github:  blakeembrey
   npm:     blakeembrey
   twitter: blakeembrey
   email:   hello@blakeembrey.com

# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has
   - avatar      # gravatar displayed on npm website
